[package]
authors = ["Alex Whitney <adwhit@fastmail.com>"]
name = "openapi3-bootstrap"
version = "0.1.0"
[dependencies]
Inflector = "0.10.1"
error-chain = "0.10.0"
quote = "0.3.15"
rustfmt = "0.9.0"
serde = "1.0.10"
serde_codegen = "0.9.0"
serde_derive = "1.0.10"
serde_json = "1.0.2"
serde_yaml = "0.7.1"
